"""Deterministic bilingual reports derived from the committed snapshot."""

import json
from pathlib import Path
from .data import ROOT, aggregate, load_snapshot, read_json, source_hashes, task_id, validate_repository


def artifacts(root=ROOT):
    errors = validate_repository(root)
    if errors:
        raise ValueError("\n".join(errors))
    manifest, rows, config = load_snapshot(root)
    summary = aggregate(manifest, rows, config)
    summary["sources_sha256"] = source_hashes(root)
    audit = read_json(root / "ctf/bench27/snapshot_audit.json")
    summary["raw_log_audit"] = {"snapshot_match": audit["identity_match"] and audit["value_differences"] == 0,
                                "sample_status_counts": audit["sample_status_counts"],
                                "raw_log_files": len(audit["raw_logs_sha256"])}
    opus = read_json(root / "ctf/bench27/opus_runs.json")
    summary["frontier_reference"] = {
        "label": "Opus-4.8 (historical project label; different scaffold)",
        "solved_tasks": sum(r["n"] > 0 for r in opus.values()),
        "solved_attempts": sum(r["n"] for r in opus.values()),
        "attempts": sum(r["t"] for r in opus.values()),
        "comparable_to_main_models": False,
    }
    result = {"summary.json": json.dumps(summary, ensure_ascii=False, indent=2) + "\n"}
    for lang in ("en", "zh-TW"):
        zh = lang == "zh-TW"
        title = "Bench27 結果快照" if zh else "Bench27 results snapshot"
        note = ("由 `python -m ais3_bench report` 產生。來源是已提交的 JSON；不呼叫 API、不重跑模型。"
                if zh else "Generated by `python -m ais3_bench report` from committed JSON; no API calls or model reruns.")
        text = [f"# {title}", "", "[繁體中文](README.zh-TW.md) | [English](README.md)", "", note, "",
                f"27 tasks × 6 models × 5 epochs = {summary['expected_attempts']} planned; "
                f"{summary['valid_attempts']} valid; {len(summary['missing_attempts'])} absent from snapshot.", "",
                ("缺少的 7 格不計入有效樣本分母。本次以本機原始 logs 核對：3 個 sample error、4 個零生成，"
                 "803 筆身份、評分、時間與截斷提交皆與快照一致。另有 60 筆較舊 run 被整批取代。"
                 if zh else "The 7 excluded attempts were checked against local raw logs: 3 sample errors and 4 zero-generation samples. "
                 "All 803 identities, scores, timings and truncated submissions match the snapshot. Another 60 attempts belong to superseded runs."), "",
                "[Retrospective audit / 回溯稽核](../ctf/bench27/snapshot_audit.json) · [Summary / 摘要](summary.json)", "",
                "## " + ("至少成功一次的題數" if zh else "Tasks solved at least once"), "",
                ("這是最多五次有效嘗試的觀察覆蓋率，不是單次成功率，也不是無偏 pass@5 估計。"
                 if zh else "Observed coverage over up to five valid attempts; not single-attempt accuracy or an unbiased pass@5 estimate."), "",
                "| Model | Solved / 27 | crypto / 6 | rev / 4 | forensics / 4 | misc / 5 | web / 4 | pwn / 4 |",
                "|---|---:|---:|---:|---:|---:|---:|---:|"]
        for m in reversed(summary["models"]):
            vals = [m["model_full"], f"{m['solved_tasks']}/27"]
            vals += [f"{m['categories'][c]['solved_tasks']}/{m['categories'][c]['total_tasks']}"
                     for c in manifest["categories"]]
            text.append("| " + " | ".join(vals) + " |")
        text += ["", "## " + ("有效嘗試成功率" if zh else "Accuracy per valid attempt"), "",
                 "| Model | contaminated | recent2026 | deep_hard | Old − recent (pp) |",
                 "|---|---:|---:|---:|---:|"]
        for m in summary["models"]:
            vals = [m["model_full"]]
            for a in m["arms"].values():
                vals.append(f"{a['solved']}/{a['valid_attempts']} ({a['accuracy']:.1%})" if a["valid_attempts"] else "N/A")
            gap = m["gap_percentage_points"]
            vals.append(f"{gap:+.1f}" if gap is not None else "N/A")
            text.append("| " + " | ".join(vals) + " |")
        text += ["", ("年份差距是描述性結果，無法單獨歸因於訓練資料污染。兩組類別數量並非完全對稱，"
                      "且使用不同評分器。重複 epoch 也不是 803 個獨立題目。"
                      if zh else "The temporal gap is descriptive, not causal evidence of training contamination. "
                      "The arms differ in category counts and scorers. Repeated epochs are not 803 independent tasks."), "",
                 "## " + ("Frontier 參考與簡報差異" if zh else "Frontier reference and slide discrepancy"), "",
                 ("目前 `opus_runs.json` 為 27/27 題、119/131 次成功；簡報第 22、34 頁為 26/27。"
                  "兩者不可靜默合併，且使用不同 scaffold，不能和主表當成相同條件的排名。"
                  if zh else "Current `opus_runs.json` reports 27/27 tasks and 119/131 successful attempts; slides 22 and 34 "
                  "report 26/27. These snapshots must not be silently merged. The frontier uses a different scaffold and "
                  "does not belong in a same-condition ranking with the main models."), "",
                 (f"樣本 `total_time` 加總為 {summary['summed_sample_hours']:.2f} 小時；此值包含重疊執行時間，"
                  "不是整場實驗的日曆耗時，也不是金額。"
                  if zh else f"Summed sample `total_time`: {summary['summed_sample_hours']:.2f} hours. "
                  "This includes overlapping execution; it is neither experiment wall-clock duration nor monetary cost."), "",
                 "[Methodology / 方法](../docs/" + lang + "/METHODOLOGY.md) · "
                 "[Evidence gaps / 待補資料](../docs/" + lang + "/EVIDENCE_GAPS.md)", ""]
        result["README.zh-TW.md" if zh else "README.md"] = "\n".join(text)
    catalog = ["# Bench27 task catalog / 題目索引", "",
               "Generated from MANIFEST.json and opus_runs.json; IDs join the harness and companion analysis.", "",
               "`needs_docker` in historical metadata means a victim service, not whether an agent sandbox is required.", "",
               "| Analysis ID | Harness ID | Arm | Category | Difficulty | Source & checkpoint |",
               "|---|---|---|---|---|---|"]
    for p in manifest["problems"]:
        tid = task_id(p)
        catalog.append(f"| {opus[tid]['clear']} | `{tid}` | {p['arm']} | {p['category']} | {p['difficulty']} | "
                       f"[{p['source']}](../ctf/bench27/{p['dir']}/README.md) · "
                       f"[steps](../ctf/bench27/{p['dir']}/checkpoints.json) |")
    result["TASK_CATALOG.md"] = "\n".join(catalog) + "\n"
    return result


def write_reports(directory, check=False, root=ROOT):
    outputs = artifacts(root)
    directory = Path(directory)
    if check:
        stale = [name for name, content in outputs.items()
                 if not (directory / name).is_file() or (directory / name).read_text(encoding="utf-8") != content]
        if stale:
            raise ValueError("Stale/missing reports: " + ", ".join(stale))
    else:
        directory.mkdir(parents=True, exist_ok=True)
        for name, content in outputs.items():
            (directory / name).write_text(content, encoding="utf-8")
    return list(outputs)
